apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: haiip-dev

bases:
  - ../../base

namePrefix: dev-

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: haiip-api
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: haiip-worker

configMapGenerator:
  - name: haiip-config
    behavior: merge
    literals:
      - APP_ENV=development
      - LOG_LEVEL=DEBUG

images:
  - name: haiip-api
    newName: ghcr.io/aliipou/haiip-api
    newTag: dev
  - name: haiip-worker
    newName: ghcr.io/aliipou/haiip-worker
    newTag: dev
